#!/usr/bin/env bash
set -uo pipefail

# PreToolUse hook: block Edit/Write to sensitive or generated files.
# Registered in .claude/settings.json with matcher "Edit|Write".
# Prevents accidental writes to lockfiles, env files, and directories
# that should only be modified by tooling (pnpm install, git, etc.).

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | grep -oP '"file_path"\s*:\s*"\K[^"]+' | head -1)

if [[ -z "${FILE_PATH:-}" ]]; then
    exit 0
fi

# Block env files (secrets), but allow documentation templates like .env.example.
if echo "$FILE_PATH" | grep -qE '\.env($|\.)' && ! echo "$FILE_PATH" | grep -qE '\.env\.(example|sample|template)$'; then
    echo "Blocked: never write .env files directly — they may contain secrets. Use .env.example for documenting variables." >&2
    exit 2
fi

# Block lockfile (generated by pnpm install).
if echo "$FILE_PATH" | grep -qE '(^|/)pnpm-lock\.yaml$'; then
    echo "Blocked: pnpm-lock.yaml is generated by pnpm install — do not edit manually." >&2
    exit 2
fi

# Block node_modules (managed by pnpm).
if echo "$FILE_PATH" | grep -qE '(^|/)node_modules/'; then
    echo "Blocked: node_modules/ is managed by pnpm — do not edit manually." >&2
    exit 2
fi

# Block .git internals.
if echo "$FILE_PATH" | grep -qE '(^|/)\.git/'; then
    echo "Blocked: .git/ is managed by git — do not edit manually." >&2
    exit 2
fi

exit 0
