packages:
    - apps/**
    - packages/**

onlyBuiltDependencies:
    - agent-browser
    - "@parcel/watcher"
    - core-js
    - esbuild
    - msw
    - netlify-cli
    - protobufjs
    - sharp
    - unix-dgram
